name: WEB tests

env:
  OS: ubuntu-latest

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Скачивание selenoid"
        run: curl -s https://aerokube.com/cm/bash  | bash
      - name: "Расширение прав на запуск selenoid"
        run: chmod +x ./cm
      - name: "Запуск selenoid"
        run: ./cm selenoid start --vnc
      - name: "Запуск selenoid-ui"
        run: ./cm selenoid-ui start
      - name: "Использование ветки main репозитория"
        uses: actions/checkout@v1
      - name: "Запуск тестов"
        run: mvn clean test
        continue-on-error: true
      - name: "Генерация allure-report"
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: "Создание ветки gh-pages содержащей allure report"
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history